# Generated by Django 4.2.5 on 2023-10-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0002_chat_delete_query'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='Topic',
        ),
    ]
