# Generated by Django 4.2.5 on 2023-10-04 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0003_rename_chat_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('Content', models.CharField(max_length=1000)),
                ('Date', models.IntegerField()),
                ('Topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions_app.topic')),
            ],
        ),
    ]
