# Generated by Django 4.2.5 on 2023-09-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_topic_delete_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='answer',
            field=models.TextField(default='default_value_here'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
