# Generated by Django 4.2.5 on 2023-09-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_topic_answer_alter_topic_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='question',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='answer',
        ),
    ]
